name: buildx Docker Image CI

on:
  workflow_dispatch


jobs:


      
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - name: manual docker login
        env:
          DockerUserName: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login docker.io
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: manual docker login
        env:
          DockerUserName: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login docker.io
      -  
        name: Login to DockerHub
        env:
          DockerUserName: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: DockerUserName   # ${{ secrets.DOCKER_USERNAME }}
          password: DockerPassword   # ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: eagle840/bullseye:latest
