name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: manual docker login
      env:
        DockerUserName: ${{ secrets.DOCKER_USERNAME }}
        DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login docker.io
  
    - name: Build the Docker image
      # run: docker build . --file ./ubuntu/Dockerfile --tag codeserver:$(date +%s)
      run: docker build . --file ./ubuntu/Dockerfile --tag codeserver
      
    - name: Tag image
      # tag the image for upload
      run: docker tag codeserver eagle840/e8codeserver:latest
      
      
    - name: Push to DockerHub
      run: docker push docker.io/eagle840/e8codeserver:latest
