name: Test Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bullseye:latest
    - name: list images
      run: docker images
      
    - name: manual docker login
      env:
        DockerUserName: ${{ secrets.DOCKER_USERNAME }}
        DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login docker.io
  
    - name: Tag image
      # tag the image for upload
      run: docker tag bullseye:latest eagle840/alpine:latest
      
      
    - name: Push to DockerHub
      run: |
        docker login
        docker push  docker.io/eagle840/alpine:latest
